version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    command: server /data --address ":9000"
    environment:
      - MINIO_ACCESS_KEY=adminadmin
      - MINIO_SECRET_KEY=adminadmin
    volumes:
      - ./minio/minio-storage:/data
      - ./minio/minio-config:/root/.minio
    restart: unless-stopped

  db:
    image: postgres:12.2
    volumes:
      - ./db_data_ps:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=phoenix
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
