image: docker:19.03.0

services:
  - docker:19.03-dind


stages:
  - build
  - deploy
 
variables:
  #CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  #DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"


cache:
  paths:
    - node_modules/

build:
  services:
    - openjdk:11.0.9.1-jdk
  stage: build
  #before_script:
  #  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - mvn -Pdev  jib:dockerBuild -Dimage=$CI_REGISTRY_IMAGE:prod
  only:
    - master

deploy:
  stage: deploy
  services:
    - docker:19.03-dind
  script:
    - docker push $CI_REGISTRY_IMAGE:prod
  only:
    - master

