image: docker:19.03.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
  
  
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  
build:
  services:
    - ${CI_REGISTRY}/sysadmins/sysadmin-tools/maven:3.6.3-jdk-11
  stage: build
  script:
    - ./mvnw -Pdev  jib:dockerBuild -Dimage=$CI_REGISTRY_IMAGE:prod
  only:
    - master

deploy:
  stage: deploy
  services:
    - docker:19.03-dind
  script:
    - docker push $CI_REGISTRY_IMAGE:prod

