image: $CI_REGISTRY_IMAGE/jhipster:latest

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .maven/
stages:
  - build
  - analyze
  - package
  - release
  - deploy
before_script:
  - export NG_CLI_ANALYTICS="false"
  - export MAVEN_USER_HOME=`pwd`/.maven
  - export TAG=$CI_COMMIT_BRANCH && [[ "$CI_COMMIT_BRANCH" == "master" ]] && TAG="prod"

maven-compile:
  stage: build
  script:
    - ./mvnw -ntp compile -P-webpack -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/classes/
      - target/generated-sources/
    expire_in: 1 day
  only:
    - master

maven-package:
  stage: package
  script:
    - ./mvnw -ntp verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/*.jar
      - target/classes
    expire_in: 1 day
  only:
    - master

docker-push:
  stage: release
  variables:
    REGISTRY_URL: $CI_REGISTRY
  dependencies:
    - maven-package
  script:
    - export IMAGE_TAG = '${CI_REGISTRY_IMAGE}:${TAG}'
    - ./mvnw -ntp compile jib:build -Pprod -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=gitlab-ci-token  -Djib.to.auth.password=$CI_BUILD_TOKEN -Dmaven.repo.local=$MAVEN_USER_HOME
  only:
    - master
    - staging
