version: '2'
services:
  hugoisep-app:
    image: hugoisep
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/app_backoffice
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    volumes:
    - ./images:/images
  #hugoisep-postgresql:
  # extends:
  #  file: postgresql.yml
  # service: hugoisep-postgresql
