version: '2'
services:
  backoffice-je-app:
    image: backoffice-je
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/app_backoffice
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    volumes:
      - ./images:/images

  confirmation-page:
    image: 'registry.dev.juniorisep.com/application-consultants-globale/confirmation-page'
    ports:
      - 5000:5000
  #backofficeje-postgresql:
  # extends:
  #  file: postgresql.yml
  # service: backofficeje-postgresql
